//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bingo.WcfServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://schemas.datacontract.org/2004/07/WcfBingo")]
    [System.SerializableAttribute()]
    public partial class Menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReglasDeJuego", Namespace="http://schemas.datacontract.org/2004/07/WcfBingo")]
    [System.SerializableAttribute()]
    public partial class ReglasDeJuego : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeInstruccionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeInstrucciones {
            get {
                return this.MensajeInstruccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeInstruccionesField, value) != true)) {
                    this.MensajeInstruccionesField = value;
                    this.RaisePropertyChanged("MensajeInstrucciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServicio.IWCFBingo")]
    public interface IWCFBingo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBingo/MENU", ReplyAction="http://tempuri.org/IWCFBingo/MENUResponse")]
        Bingo.WcfServicio.Menu MENU(int opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBingo/MENU", ReplyAction="http://tempuri.org/IWCFBingo/MENUResponse")]
        System.Threading.Tasks.Task<Bingo.WcfServicio.Menu> MENUAsync(int opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBingo/ReglasDeJuego", ReplyAction="http://tempuri.org/IWCFBingo/ReglasDeJuegoResponse")]
        Bingo.WcfServicio.ReglasDeJuego ReglasDeJuego();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBingo/ReglasDeJuego", ReplyAction="http://tempuri.org/IWCFBingo/ReglasDeJuegoResponse")]
        System.Threading.Tasks.Task<Bingo.WcfServicio.ReglasDeJuego> ReglasDeJuegoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFBingoChannel : Bingo.WcfServicio.IWCFBingo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFBingoClient : System.ServiceModel.ClientBase<Bingo.WcfServicio.IWCFBingo>, Bingo.WcfServicio.IWCFBingo {
        
        public WCFBingoClient() {
        }
        
        public WCFBingoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFBingoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFBingoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFBingoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bingo.WcfServicio.Menu MENU(int opcion) {
            return base.Channel.MENU(opcion);
        }
        
        public System.Threading.Tasks.Task<Bingo.WcfServicio.Menu> MENUAsync(int opcion) {
            return base.Channel.MENUAsync(opcion);
        }
        
        public Bingo.WcfServicio.ReglasDeJuego ReglasDeJuego() {
            return base.Channel.ReglasDeJuego();
        }
        
        public System.Threading.Tasks.Task<Bingo.WcfServicio.ReglasDeJuego> ReglasDeJuegoAsync() {
            return base.Channel.ReglasDeJuegoAsync();
        }
    }
}
